-- CreateTable
CREATE TABLE "TREVAG" (
    "CODVAG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODEMP" BIGINT NOT NULL,
    "TITULO" TEXT NOT NULL,
    "DESCRVAG" TEXT,
    "LOCAL" TEXT,
    "SENIORIDADE" TEXT,
    "STATUS" TEXT NOT NULL DEFAULT 'RASCUNHO',
    "URGENTE" CHAR(1) NOT NULL DEFAULT 'N',
    "DHPUB" TIMESTAMP(3),
    "CODUSUAPROV" BIGINT,
    "DHAPROV" TIMESTAMP(3),
    "OBSAPROV" TEXT,
    "MOTIVOCANCEL" TEXT,
    "CODCANDCONTRATADO" BIGINT,
    "VLRSALMIN" DECIMAL(15,2),
    "VLRSALMAX" DECIMAL(15,2),
    "SALAVISTA" CHAR(1) NOT NULL DEFAULT 'N',
    "MODELOTRAB" TEXT,
    "TIPOCONTRATO" TEXT,
    "CODDEP" BIGINT,
    "CODCAR" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TREVAG_pkey" PRIMARY KEY ("CODVAG")
);

-- CreateTable
CREATE TABLE "TREVAGREQ" (
    "CODVAGREQ" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODVAG" BIGINT NOT NULL,
    "DESCRREQ" TEXT NOT NULL,
    "TIPOREQ" TEXT NOT NULL DEFAULT 'OBRIGATORIO',
    "KNOCKOUT" CHAR(1) NOT NULL DEFAULT 'N',
    "ORDEM" INTEGER NOT NULL DEFAULT 1,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TREVAGREQ_pkey" PRIMARY KEY ("CODVAGREQ")
);

-- CreateTable
CREATE TABLE "TREVAGPER" (
    "CODVAGPER" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODVAG" BIGINT NOT NULL,
    "PERGUNTA" TEXT NOT NULL,
    "TIPORESP" TEXT NOT NULL DEFAULT 'SIM_NAO',
    "OBRIGATORIA" CHAR(1) NOT NULL DEFAULT 'S',
    "RESPELIMINA" TEXT,
    "ORDEM" INTEGER NOT NULL DEFAULT 1,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TREVAGPER_pkey" PRIMARY KEY ("CODVAGPER")
);

-- CreateTable
CREATE TABLE "TRECANAL" (
    "CODCANAL" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMECANAL" TEXT NOT NULL,
    "TIPOCANAL" TEXT NOT NULL DEFAULT 'manual',
    "VLRCUSTOMES" DECIMAL(15,2),
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TRECANAL_pkey" PRIMARY KEY ("CODCANAL")
);

-- CreateTable
CREATE TABLE "TREVAGCANAL" (
    "CODVAGCANAL" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODVAG" BIGINT NOT NULL,
    "CODCANAL" BIGINT NOT NULL,
    "IDEXTERNO" TEXT,
    "URLEXTERNA" TEXT,
    "DHPUB" TIMESTAMP(3),
    "STATUS" TEXT NOT NULL DEFAULT 'PUBLICADA',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TREVAGCANAL_pkey" PRIMARY KEY ("CODVAGCANAL")
);

-- CreateTable
CREATE TABLE "TRECAND" (
    "CODCAND" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMECAND" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "FONE" TEXT,
    "CGC" TEXT,
    "LINKEDIN" TEXT,
    "CIDADE" TEXT,
    "CODUSU" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TRECAND_pkey" PRIMARY KEY ("CODCAND")
);

-- CreateTable
CREATE TABLE "TRECANDCV" (
    "CODCANDCV" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCAND" BIGINT NOT NULL,
    "ARQUIVO" TEXT NOT NULL,
    "TEXTOEXTRAIDO" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TRECANDCV_pkey" PRIMARY KEY ("CODCANDCV")
);

-- CreateTable
CREATE TABLE "TRECDT" (
    "CODCDT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODVAG" BIGINT NOT NULL,
    "CODCAND" BIGINT NOT NULL,
    "ESTAGIO" TEXT NOT NULL DEFAULT 'applied',
    "CODCANAL" BIGINT NOT NULL,
    "IDEXTERNO" TEXT,
    "RESPOSTASJSON" JSONB,
    "KNOCKOUTJSON" JSONB,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TRECDT_pkey" PRIMARY KEY ("CODCDT")
);

-- CreateTable
CREATE TABLE "TRECDTHIS" (
    "CODCDTHIS" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "TIPOEVENTO" TEXT NOT NULL,
    "ESTAGIOANT" TEXT,
    "ESTAGIONOVO" TEXT,
    "ROTULOPUB" TEXT,
    "NOTAINTERNA" TEXT,
    "TIPOATOR" TEXT NOT NULL DEFAULT 'usuario',
    "METADADOSJSON" JSONB,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TRECDTHIS_pkey" PRIMARY KEY ("CODCDTHIS")
);

-- CreateTable
CREATE TABLE "TREETPCFG" (
    "CODETPCFG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODEMP" BIGINT,
    "ESTAGIO" TEXT NOT NULL,
    "ORDEM" INTEGER NOT NULL,
    "ROTULOPUB" TEXT NOT NULL,
    "DESCRPUB" TEXT,
    "VISIVEL" CHAR(1) NOT NULL DEFAULT 'S',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,

    CONSTRAINT "TREETPCFG_pkey" PRIMARY KEY ("CODETPCFG")
);

-- CreateTable
CREATE TABLE "TREMATCH" (
    "CODMATCH" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCDT" BIGINT NOT NULL,
    "VERSAOMATCH" TEXT NOT NULL,
    "SCOREGERAL" INTEGER NOT NULL,
    "SCORECONTRATACAO" INTEGER,
    "SCORECULTURA" INTEGER,
    "DRIVERPRINCIPAL" TEXT,
    "QTDGAPSCRIT" INTEGER NOT NULL DEFAULT 0,
    "QTDGAPSMELH" INTEGER NOT NULL DEFAULT 0,
    "HASHENTRADA" TEXT NOT NULL,
    "DHCALC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TREMATCH_pkey" PRIMARY KEY ("CODMATCH")
);

-- CreateIndex
CREATE INDEX "TREVAG_CODTEN_STATUS_idx" ON "TREVAG"("CODTEN", "STATUS");

-- CreateIndex
CREATE INDEX "TREVAGREQ_CODTEN_CODVAG_idx" ON "TREVAGREQ"("CODTEN", "CODVAG");

-- CreateIndex
CREATE INDEX "TREVAGPER_CODTEN_CODVAG_idx" ON "TREVAGPER"("CODTEN", "CODVAG");

-- CreateIndex
CREATE UNIQUE INDEX "TRECANAL_CODTEN_NOMECANAL_key" ON "TRECANAL"("CODTEN", "NOMECANAL");

-- CreateIndex
CREATE INDEX "TREVAGCANAL_CODTEN_CODVAG_idx" ON "TREVAGCANAL"("CODTEN", "CODVAG");

-- CreateIndex
CREATE INDEX "TRECAND_CODTEN_CGC_idx" ON "TRECAND"("CODTEN", "CGC");

-- CreateIndex
CREATE UNIQUE INDEX "TRECAND_CODTEN_EMAIL_key" ON "TRECAND"("CODTEN", "EMAIL");

-- CreateIndex
CREATE INDEX "TRECANDCV_CODTEN_CODCAND_idx" ON "TRECANDCV"("CODTEN", "CODCAND");

-- CreateIndex
CREATE INDEX "TRECDT_CODTEN_CODVAG_ESTAGIO_idx" ON "TRECDT"("CODTEN", "CODVAG", "ESTAGIO");

-- CreateIndex
CREATE UNIQUE INDEX "TRECDT_CODVAG_CODCAND_key" ON "TRECDT"("CODVAG", "CODCAND");

-- CreateIndex
CREATE INDEX "TRECDTHIS_CODTEN_CODCDT_idx" ON "TRECDTHIS"("CODTEN", "CODCDT");

-- CreateIndex
CREATE UNIQUE INDEX "TREETPCFG_CODTEN_CODEMP_ESTAGIO_key" ON "TREETPCFG"("CODTEN", "CODEMP", "ESTAGIO");

-- CreateIndex
CREATE UNIQUE INDEX "TREMATCH_CODCDT_key" ON "TREMATCH"("CODCDT");

-- AddForeignKey
ALTER TABLE "TREVAG" ADD CONSTRAINT "TREVAG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAG" ADD CONSTRAINT "TREVAG_CODEMP_fkey" FOREIGN KEY ("CODEMP") REFERENCES "TSIEMP"("CODEMP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAG" ADD CONSTRAINT "TREVAG_CODDEP_fkey" FOREIGN KEY ("CODDEP") REFERENCES "TFPDEP"("CODDEP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAG" ADD CONSTRAINT "TREVAG_CODCAR_fkey" FOREIGN KEY ("CODCAR") REFERENCES "TFPCAR"("CODCAR") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAGREQ" ADD CONSTRAINT "TREVAGREQ_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAGREQ" ADD CONSTRAINT "TREVAGREQ_CODVAG_fkey" FOREIGN KEY ("CODVAG") REFERENCES "TREVAG"("CODVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAGPER" ADD CONSTRAINT "TREVAGPER_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAGPER" ADD CONSTRAINT "TREVAGPER_CODVAG_fkey" FOREIGN KEY ("CODVAG") REFERENCES "TREVAG"("CODVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECANAL" ADD CONSTRAINT "TRECANAL_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAGCANAL" ADD CONSTRAINT "TREVAGCANAL_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAGCANAL" ADD CONSTRAINT "TREVAGCANAL_CODVAG_fkey" FOREIGN KEY ("CODVAG") REFERENCES "TREVAG"("CODVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREVAGCANAL" ADD CONSTRAINT "TREVAGCANAL_CODCANAL_fkey" FOREIGN KEY ("CODCANAL") REFERENCES "TRECANAL"("CODCANAL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECAND" ADD CONSTRAINT "TRECAND_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECANDCV" ADD CONSTRAINT "TRECANDCV_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECANDCV" ADD CONSTRAINT "TRECANDCV_CODCAND_fkey" FOREIGN KEY ("CODCAND") REFERENCES "TRECAND"("CODCAND") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDT" ADD CONSTRAINT "TRECDT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDT" ADD CONSTRAINT "TRECDT_CODVAG_fkey" FOREIGN KEY ("CODVAG") REFERENCES "TREVAG"("CODVAG") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDT" ADD CONSTRAINT "TRECDT_CODCAND_fkey" FOREIGN KEY ("CODCAND") REFERENCES "TRECAND"("CODCAND") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDT" ADD CONSTRAINT "TRECDT_CODCANAL_fkey" FOREIGN KEY ("CODCANAL") REFERENCES "TRECANAL"("CODCANAL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDTHIS" ADD CONSTRAINT "TRECDTHIS_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECDTHIS" ADD CONSTRAINT "TRECDTHIS_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREETPCFG" ADD CONSTRAINT "TREETPCFG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREMATCH" ADD CONSTRAINT "TREMATCH_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TREMATCH" ADD CONSTRAINT "TREMATCH_CODCDT_fkey" FOREIGN KEY ("CODCDT") REFERENCES "TRECDT"("CODCDT") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) nas tabelas do Recrutamento
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TREVAG','TREVAGREQ','TREVAGPER','TRECANAL','TREVAGCANAL','TRECAND','TRECANDCV','TRECDT','TRECDTHIS','TREETPCFG','TREMATCH'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
