-- CreateTable
CREATE TABLE "TSXDOC" (
    "CODDOC" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMEDOC" TEXT NOT NULL,
    "CONTEUDOMODELO" TEXT NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSXDOC_pkey" PRIMARY KEY ("CODDOC")
);

-- CreateTable
CREATE TABLE "TSXASSIN" (
    "CODASSIN" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODDOC" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "CONTEUDORENDERIZADO" TEXT NOT NULL,
    "HASHCONTEUDO" TEXT NOT NULL,
    "TOKENPUB" TEXT NOT NULL,
    "STATUS" TEXT NOT NULL DEFAULT 'PENDENTE',
    "DHENVIO" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHASSINATURA" TIMESTAMP(3),
    "IPASSINATURA" TEXT,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TSXASSIN_pkey" PRIMARY KEY ("CODASSIN")
);

-- CreateIndex
CREATE UNIQUE INDEX "TSXASSIN_TOKENPUB_key" ON "TSXASSIN"("TOKENPUB");

-- CreateIndex
CREATE INDEX "TSXASSIN_CODTEN_CODFUN_idx" ON "TSXASSIN"("CODTEN", "CODFUN");

-- AddForeignKey
ALTER TABLE "TSXDOC" ADD CONSTRAINT "TSXDOC_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXASSIN" ADD CONSTRAINT "TSXASSIN_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXASSIN" ADD CONSTRAINT "TSXASSIN_CODDOC_fkey" FOREIGN KEY ("CODDOC") REFERENCES "TSXDOC"("CODDOC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXASSIN" ADD CONSTRAINT "TSXASSIN_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002)
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TSXDOC','TSXASSIN'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
