-- CreateTable
CREATE TABLE "TGPPOT" (
    "CODPOT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "DESEMPENHOEIXO" INTEGER NOT NULL,
    "POTENCIALEIXO" INTEGER NOT NULL,
    "NIVELCONFIANCA" TEXT NOT NULL DEFAULT 'MEDIO',
    "EVIDENCIAS" TEXT,
    "REVISAOHUMANA" CHAR(1) NOT NULL DEFAULT 'N',
    "CARGOALVO" TEXT,
    "PRONTIDAO" TEXT,
    "CODUSUAVALIADOR" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPPOT_pkey" PRIMARY KEY ("CODPOT")
);

-- CreateIndex
CREATE INDEX "TGPPOT_CODTEN_CODFUN_idx" ON "TGPPOT"("CODTEN", "CODFUN");

-- AddForeignKey
ALTER TABLE "TGPPOT" ADD CONSTRAINT "TGPPOT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPOT" ADD CONSTRAINT "TGPPOT_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPPOT" ADD CONSTRAINT "TGPPOT_CODUSUAVALIADOR_fkey" FOREIGN KEY ("CODUSUAVALIADOR") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — avaliação de potencial é dado do funcionário, por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPPOT'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
