-- CreateTable
CREATE TABLE "TGPMOD360" (
    "CODMOD" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCAR" BIGINT NOT NULL,
    "NOME" TEXT NOT NULL,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPMOD360_pkey" PRIMARY KEY ("CODMOD")
);

-- CreateTable
CREATE TABLE "TGPMOD360AVAL" (
    "CODMODAVAL" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODMOD" BIGINT NOT NULL,
    "TIPO" TEXT NOT NULL,
    "PESO" INTEGER NOT NULL DEFAULT 1,
    "OBRIGATORIO" CHAR(1) NOT NULL DEFAULT 'S',
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TGPMOD360AVAL_pkey" PRIMARY KEY ("CODMODAVAL")
);

-- CreateTable
CREATE TABLE "TGPAVALPART" (
    "CODAVALPART" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODAVAL" BIGINT NOT NULL,
    "TIPO" TEXT NOT NULL,
    "PESO" INTEGER NOT NULL DEFAULT 1,
    "CODUSUAVALIADOR" BIGINT,
    "STATUS" TEXT NOT NULL DEFAULT 'PENDENTE',
    "DHCONCLUSAO" TIMESTAMP(3),
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPAVALPART_pkey" PRIMARY KEY ("CODAVALPART")
);

-- CreateTable
CREATE TABLE "TGPNOTAPART" (
    "CODNOTAPART" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODAVALPART" BIGINT NOT NULL,
    "CODCOMP" BIGINT NOT NULL,
    "NOTA" INTEGER NOT NULL,
    "COMENTARIO" TEXT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPNOTAPART_pkey" PRIMARY KEY ("CODNOTAPART")
);

-- CreateIndex
CREATE UNIQUE INDEX "TGPMOD360_CODTEN_CODCAR_key" ON "TGPMOD360"("CODTEN", "CODCAR");

-- CreateIndex
CREATE UNIQUE INDEX "TGPMOD360AVAL_CODMOD_TIPO_key" ON "TGPMOD360AVAL"("CODMOD", "TIPO");

-- CreateIndex
CREATE INDEX "TGPAVALPART_CODTEN_CODAVAL_idx" ON "TGPAVALPART"("CODTEN", "CODAVAL");

-- CreateIndex
CREATE INDEX "TGPNOTAPART_CODTEN_CODAVALPART_idx" ON "TGPNOTAPART"("CODTEN", "CODAVALPART");

-- CreateIndex
CREATE UNIQUE INDEX "TGPNOTAPART_CODAVALPART_CODCOMP_key" ON "TGPNOTAPART"("CODAVALPART", "CODCOMP");

-- AddForeignKey
ALTER TABLE "TGPMOD360" ADD CONSTRAINT "TGPMOD360_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMOD360" ADD CONSTRAINT "TGPMOD360_CODCAR_fkey" FOREIGN KEY ("CODCAR") REFERENCES "TFPCAR"("CODCAR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMOD360AVAL" ADD CONSTRAINT "TGPMOD360AVAL_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMOD360AVAL" ADD CONSTRAINT "TGPMOD360AVAL_CODMOD_fkey" FOREIGN KEY ("CODMOD") REFERENCES "TGPMOD360"("CODMOD") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPAVALPART" ADD CONSTRAINT "TGPAVALPART_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPAVALPART" ADD CONSTRAINT "TGPAVALPART_CODAVAL_fkey" FOREIGN KEY ("CODAVAL") REFERENCES "TGPAVAL"("CODAVAL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPAVALPART" ADD CONSTRAINT "TGPAVALPART_CODUSUAVALIADOR_fkey" FOREIGN KEY ("CODUSUAVALIADOR") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPNOTAPART" ADD CONSTRAINT "TGPNOTAPART_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPNOTAPART" ADD CONSTRAINT "TGPNOTAPART_CODAVALPART_fkey" FOREIGN KEY ("CODAVALPART") REFERENCES "TGPAVALPART"("CODAVALPART") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPNOTAPART" ADD CONSTRAINT "TGPNOTAPART_CODCOMP_fkey" FOREIGN KEY ("CODCOMP") REFERENCES "TGPCOMP"("CODCOMP") ON DELETE RESTRICT ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — modelo/participante/nota 360 são dados do tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPMOD360','TGPMOD360AVAL','TGPAVALPART','TGPNOTAPART'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
