-- CreateTable
CREATE TABLE "TGPIAINS" (
    "CODIAINS" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "TIPO" TEXT NOT NULL,
    "CONTEUDOJSON" JSONB NOT NULL,
    "HASHENTRADA" TEXT NOT NULL,
    "PROVEDOR" TEXT,
    "MODELOUSADO" TEXT,
    "VERSAOPROMPT" TEXT,
    "DURACAOMS" INTEGER,
    "STATUS" TEXT NOT NULL DEFAULT 'OK',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TGPIAINS_pkey" PRIMARY KEY ("CODIAINS")
);

-- CreateIndex
CREATE INDEX "TGPIAINS_CODTEN_CODFUN_TIPO_idx" ON "TGPIAINS"("CODTEN", "CODFUN", "TIPO");

-- AddForeignKey
ALTER TABLE "TGPIAINS" ADD CONSTRAINT "TGPIAINS_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPIAINS" ADD CONSTRAINT "TGPIAINS_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — insight de IA de desempenho é dado do funcionário, por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPIAINS'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
