-- CreateTable
CREATE TABLE "TGPMETA" (
    "CODMETA" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "CODCICLO" BIGINT,
    "TITULO" TEXT NOT NULL,
    "DESCRICAO" TEXT,
    "PESO" INTEGER NOT NULL DEFAULT 1,
    "PRAZO" DATE,
    "PROGRESSO" INTEGER NOT NULL DEFAULT 0,
    "CANCELADA" CHAR(1) NOT NULL DEFAULT 'N',
    "IMPACTOAVALIACAO" TEXT,
    "RESULTADO" TEXT,
    "CODUSURESP" BIGINT,
    "CODPDI" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPMETA_pkey" PRIMARY KEY ("CODMETA")
);

-- CreateTable
CREATE TABLE "TGPMETAPROG" (
    "CODMETAPROG" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODMETA" BIGINT NOT NULL,
    "PROGRESSO" INTEGER NOT NULL,
    "COMENTARIO" TEXT,
    "EVIDENCIA" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TGPMETAPROG_pkey" PRIMARY KEY ("CODMETAPROG")
);

-- CreateIndex
CREATE INDEX "TGPMETA_CODTEN_CODFUN_idx" ON "TGPMETA"("CODTEN", "CODFUN");

-- CreateIndex
CREATE INDEX "TGPMETAPROG_CODTEN_CODMETA_idx" ON "TGPMETAPROG"("CODTEN", "CODMETA");

-- AddForeignKey
ALTER TABLE "TGPMETA" ADD CONSTRAINT "TGPMETA_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMETA" ADD CONSTRAINT "TGPMETA_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMETA" ADD CONSTRAINT "TGPMETA_CODCICLO_fkey" FOREIGN KEY ("CODCICLO") REFERENCES "TGPCICLO"("CODCICLO") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMETA" ADD CONSTRAINT "TGPMETA_CODUSURESP_fkey" FOREIGN KEY ("CODUSURESP") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMETA" ADD CONSTRAINT "TGPMETA_CODPDI_fkey" FOREIGN KEY ("CODPDI") REFERENCES "TGPPDI"("CODPDI") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMETAPROG" ADD CONSTRAINT "TGPMETAPROG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPMETAPROG" ADD CONSTRAINT "TGPMETAPROG_CODMETA_fkey" FOREIGN KEY ("CODMETA") REFERENCES "TGPMETA"("CODMETA") ON DELETE RESTRICT ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — metas e seu progresso são dados do funcionário, por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPMETA','TGPMETAPROG'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
