-- AlterTable
ALTER TABLE "TREVAG" ADD COLUMN     "CODUSURESP" BIGINT;

-- AddForeignKey
ALTER TABLE "TREVAG" ADD CONSTRAINT "TREVAG_CODUSURESP_fkey" FOREIGN KEY ("CODUSURESP") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;

