-- AlterTable
ALTER TABLE "TRECAND" ADD COLUMN     "DISPAVISODIAS" INTEGER,
ADD COLUMN     "DISPDATA" DATE,
ADD COLUMN     "DISPTIPO" TEXT,
ADD COLUMN     "PRETENSAONEGOCIAVEL" CHAR(1),
ADD COLUMN     "PRETENSAOSALARIAL" DECIMAL(15,2);

-- CreateTable
CREATE TABLE "TRECANDFOR" (
    "CODFOR" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCAND" BIGINT NOT NULL,
    "NIVEL" TEXT NOT NULL,
    "CURSO" TEXT,
    "INSTITUICAO" TEXT,
    "SITUACAO" TEXT NOT NULL DEFAULT 'CONCLUIDO',
    "ANOCONCLUSAO" INTEGER,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TRECANDFOR_pkey" PRIMARY KEY ("CODFOR")
);

-- CreateIndex
CREATE INDEX "TRECANDFOR_CODTEN_CODCAND_idx" ON "TRECANDFOR"("CODTEN", "CODCAND");

-- AddForeignKey
ALTER TABLE "TRECANDFOR" ADD CONSTRAINT "TRECANDFOR_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TRECANDFOR" ADD CONSTRAINT "TRECANDFOR_CODCAND_fkey" FOREIGN KEY ("CODCAND") REFERENCES "TRECAND"("CODCAND") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — formação é dado do candidato, por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TRECANDFOR'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
