-- AlterTable
ALTER TABLE "TGPMOD360" ADD COLUMN     "CODCAR" BIGINT;

-- AddForeignKey
ALTER TABLE "TGPMOD360" ADD CONSTRAINT "TGPMOD360_CODCAR_fkey" FOREIGN KEY ("CODCAR") REFERENCES "TFPCAR"("CODCAR") ON DELETE SET NULL ON UPDATE CASCADE;

