-- CreateTable
CREATE TABLE "TGPFEED" (
    "CODFEED" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "CODPDI" BIGINT,
    "TIPO" TEXT NOT NULL DEFAULT 'NEUTRO',
    "CONTEXTO" TEXT NOT NULL DEFAULT 'ACOMPANHAMENTO',
    "MENSAGEM" TEXT NOT NULL,
    "CODUSUAUTOR" BIGINT NOT NULL,
    "CIENTEFUN" CHAR(1),
    "DHCIENTE" TIMESTAMP(3),
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TGPFEED_pkey" PRIMARY KEY ("CODFEED")
);

-- CreateIndex
CREATE INDEX "TGPFEED_CODTEN_CODFUN_idx" ON "TGPFEED"("CODTEN", "CODFUN");

-- AddForeignKey
ALTER TABLE "TGPFEED" ADD CONSTRAINT "TGPFEED_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPFEED" ADD CONSTRAINT "TGPFEED_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPFEED" ADD CONSTRAINT "TGPFEED_CODPDI_fkey" FOREIGN KEY ("CODPDI") REFERENCES "TGPPDI"("CODPDI") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPFEED" ADD CONSTRAINT "TGPFEED_CODUSUAUTOR_fkey" FOREIGN KEY ("CODUSUAUTOR") REFERENCES "TSIUSU"("CODUSU") ON DELETE RESTRICT ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002) — feedback é dado do funcionário, por tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPFEED'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
