-- AlterTable
ALTER TABLE "TRECDT" ADD COLUMN     "CODFUN" BIGINT;

-- AddForeignKey
ALTER TABLE "TRECDT" ADD CONSTRAINT "TRECDT_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE SET NULL ON UPDATE CASCADE;

