-- CreateTable
CREATE TABLE "TGPCICLO" (
    "CODCICLO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DESCRICAO" TEXT,
    "DTINICIO" DATE NOT NULL,
    "DTFIM" DATE NOT NULL,
    "STATUS" TEXT NOT NULL DEFAULT 'RASCUNHO',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPCICLO_pkey" PRIMARY KEY ("CODCICLO")
);

-- CreateTable
CREATE TABLE "TGPCOMP" (
    "CODCOMP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCICLO" BIGINT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DESCRICAO" TEXT,
    "PESO" INTEGER NOT NULL DEFAULT 1,
    "ORDEM" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "TGPCOMP_pkey" PRIMARY KEY ("CODCOMP")
);

-- CreateTable
CREATE TABLE "TGPAVAL" (
    "CODAVAL" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCICLO" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "CODUSUAVALIADOR" BIGINT,
    "STATUS" TEXT NOT NULL DEFAULT 'PENDENTE',
    "COMENTARIOGERAL" TEXT,
    "DHCONCLUSAO" TIMESTAMP(3),
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPAVAL_pkey" PRIMARY KEY ("CODAVAL")
);

-- CreateTable
CREATE TABLE "TGPNOTA" (
    "CODNOTA" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODAVAL" BIGINT NOT NULL,
    "CODCOMP" BIGINT NOT NULL,
    "NOTA" INTEGER NOT NULL,
    "COMENTARIO" TEXT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPNOTA_pkey" PRIMARY KEY ("CODNOTA")
);

-- CreateIndex
CREATE INDEX "TGPCICLO_CODTEN_STATUS_idx" ON "TGPCICLO"("CODTEN", "STATUS");

-- CreateIndex
CREATE INDEX "TGPCOMP_CODTEN_CODCICLO_idx" ON "TGPCOMP"("CODTEN", "CODCICLO");

-- CreateIndex
CREATE INDEX "TGPAVAL_CODTEN_CODCICLO_idx" ON "TGPAVAL"("CODTEN", "CODCICLO");

-- CreateIndex
CREATE UNIQUE INDEX "TGPAVAL_CODCICLO_CODFUN_key" ON "TGPAVAL"("CODCICLO", "CODFUN");

-- CreateIndex
CREATE INDEX "TGPNOTA_CODTEN_CODAVAL_idx" ON "TGPNOTA"("CODTEN", "CODAVAL");

-- CreateIndex
CREATE UNIQUE INDEX "TGPNOTA_CODAVAL_CODCOMP_key" ON "TGPNOTA"("CODAVAL", "CODCOMP");

-- AddForeignKey
ALTER TABLE "TGPCICLO" ADD CONSTRAINT "TGPCICLO_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPCOMP" ADD CONSTRAINT "TGPCOMP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPCOMP" ADD CONSTRAINT "TGPCOMP_CODCICLO_fkey" FOREIGN KEY ("CODCICLO") REFERENCES "TGPCICLO"("CODCICLO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPAVAL" ADD CONSTRAINT "TGPAVAL_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPAVAL" ADD CONSTRAINT "TGPAVAL_CODCICLO_fkey" FOREIGN KEY ("CODCICLO") REFERENCES "TGPCICLO"("CODCICLO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPAVAL" ADD CONSTRAINT "TGPAVAL_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPAVAL" ADD CONSTRAINT "TGPAVAL_CODUSUAVALIADOR_fkey" FOREIGN KEY ("CODUSUAVALIADOR") REFERENCES "TSIUSU"("CODUSU") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPNOTA" ADD CONSTRAINT "TGPNOTA_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPNOTA" ADD CONSTRAINT "TGPNOTA_CODAVAL_fkey" FOREIGN KEY ("CODAVAL") REFERENCES "TGPAVAL"("CODAVAL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPNOTA" ADD CONSTRAINT "TGPNOTA_CODCOMP_fkey" FOREIGN KEY ("CODCOMP") REFERENCES "TGPCOMP"("CODCOMP") ON DELETE RESTRICT ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — ciclo/competência/avaliação/nota são dados do tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPCICLO','TGPCOMP','TGPAVAL','TGPNOTA'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
