-- CreateTable
CREATE TABLE "TGPTREINO" (
    "CODTREINO" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DESCRICAO" TEXT,
    "TIPO" TEXT NOT NULL DEFAULT 'CURSO',
    "COMPETENCIA" TEXT,
    "CARGAHORARIA" INTEGER,
    "OBRIGATORIO" CHAR(1) NOT NULL DEFAULT 'N',
    "VALIDADEMESES" INTEGER,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPTREINO_pkey" PRIMARY KEY ("CODTREINO")
);

-- CreateTable
CREATE TABLE "TGPTREINOMAT" (
    "CODMAT" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "CODTREINO" BIGINT NOT NULL,
    "STATUS" TEXT NOT NULL DEFAULT 'PENDENTE',
    "ORIGEM" TEXT NOT NULL DEFAULT 'GESTOR',
    "PROGRESSO" INTEGER NOT NULL DEFAULT 0,
    "JUSTIFICATIVA" TEXT,
    "DTINICIO" DATE,
    "DTCONCLUSAO" DATE,
    "DTVENCIMENTO" DATE,
    "CERTIFICADO" TEXT,
    "CODPDI" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TGPTREINOMAT_pkey" PRIMARY KEY ("CODMAT")
);

-- CreateIndex
CREATE INDEX "TGPTREINO_CODTEN_ATIVO_idx" ON "TGPTREINO"("CODTEN", "ATIVO");

-- CreateIndex
CREATE INDEX "TGPTREINOMAT_CODTEN_CODFUN_idx" ON "TGPTREINOMAT"("CODTEN", "CODFUN");

-- AddForeignKey
ALTER TABLE "TGPTREINO" ADD CONSTRAINT "TGPTREINO_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPTREINOMAT" ADD CONSTRAINT "TGPTREINOMAT_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPTREINOMAT" ADD CONSTRAINT "TGPTREINOMAT_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPTREINOMAT" ADD CONSTRAINT "TGPTREINOMAT_CODTREINO_fkey" FOREIGN KEY ("CODTREINO") REFERENCES "TGPTREINO"("CODTREINO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TGPTREINOMAT" ADD CONSTRAINT "TGPTREINOMAT_CODPDI_fkey" FOREIGN KEY ("CODPDI") REFERENCES "TGPPDI"("CODPDI") ON DELETE SET NULL ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — catálogo e matrículas de treinamento são dados do tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TGPTREINO','TGPTREINOMAT'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
