-- AlterTable
ALTER TABLE "TFPFUN" ADD COLUMN     "CODDEP" BIGINT;

-- CreateTable
CREATE TABLE "TFPDEP" (
    "CODDEP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "DESCRDEP" TEXT NOT NULL,
    "CODDEPPAI" BIGINT,
    "GRAU" INTEGER NOT NULL DEFAULT 1,
    "ANALITICO" CHAR(1) NOT NULL DEFAULT 'S',
    "CODCENCUS" BIGINT,
    "CODDEPERP" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TFPDEP_pkey" PRIMARY KEY ("CODDEP")
);

-- CreateIndex
CREATE INDEX "TFPDEP_CODTEN_idx" ON "TFPDEP"("CODTEN");

-- AddForeignKey
ALTER TABLE "TFPFUN" ADD CONSTRAINT "TFPFUN_CODDEP_fkey" FOREIGN KEY ("CODDEP") REFERENCES "TFPDEP"("CODDEP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPDEP" ADD CONSTRAINT "TFPDEP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPDEP" ADD CONSTRAINT "TFPDEP_CODDEPPAI_fkey" FOREIGN KEY ("CODDEPPAI") REFERENCES "TFPDEP"("CODDEP") ON DELETE SET NULL ON UPDATE CASCADE;


-- SelX: RLS (ADR-0002)
ALTER TABLE "TFPDEP" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TFPDEP" FORCE ROW LEVEL SECURITY;
CREATE POLICY politica_tenant ON "TFPDEP"
  USING ("CODTEN" = NULLIF(current_setting('app.codten', true), '')::bigint)
  WITH CHECK ("CODTEN" = NULLIF(current_setting('app.codten', true), '')::bigint);
