-- CreateTable
CREATE TABLE "TSXTEN" (
    "CODTEN" BIGSERIAL NOT NULL,
    "NOMETEN" TEXT NOT NULL,
    "SITUACAO" TEXT NOT NULL DEFAULT 'ATIVO',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSXTEN_pkey" PRIMARY KEY ("CODTEN")
);

-- CreateTable
CREATE TABLE "TSIEMP" (
    "CODEMP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODEMPMATRIZ" BIGINT,
    "NOMEFANTASIA" TEXT NOT NULL,
    "RAZAOSOCIAL" TEXT NOT NULL,
    "CGC" TEXT,
    "CODEMPERP" BIGINT,
    "SITUACAO" TEXT NOT NULL DEFAULT 'ATIVA',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSIEMP_pkey" PRIMARY KEY ("CODEMP")
);

-- CreateTable
CREATE TABLE "TFPCAR" (
    "CODCAR" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMECAR" TEXT NOT NULL,
    "CBO" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TFPCAR_pkey" PRIMARY KEY ("CODCAR")
);

-- CreateTable
CREATE TABLE "TSICUS" (
    "CODCENCUS" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODEMP" BIGINT,
    "DESCRCENCUS" TEXT NOT NULL,
    "CODCENCUSPAI" BIGINT,
    "ANALITICO" CHAR(1) NOT NULL DEFAULT 'S',
    "CODCENCUSERP" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSICUS_pkey" PRIMARY KEY ("CODCENCUS")
);

-- CreateTable
CREATE TABLE "TFPFUN" (
    "CODFUN" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODEMP" BIGINT NOT NULL,
    "NUMCAD" BIGINT NOT NULL,
    "NOMEFUN" TEXT NOT NULL,
    "CGC" TEXT,
    "DTNASC" DATE,
    "DTADM" DATE NOT NULL,
    "DTDEM" DATE,
    "CODCAR" BIGINT,
    "CODCENCUS" BIGINT,
    "TIPOCONTRATO" TEXT NOT NULL DEFAULT 'CLT',
    "VLRSAL" DECIMAL(15,2),
    "SITUACAO" TEXT NOT NULL DEFAULT 'ATIVO',
    "CODFUNERP" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TFPFUN_pkey" PRIMARY KEY ("CODFUN")
);

-- CreateTable
CREATE TABLE "TFPFUNHIS" (
    "CODFUNHIS" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "TIPOMUD" TEXT NOT NULL,
    "VALORANT" TEXT,
    "VALORNOVO" TEXT,
    "DTMUD" DATE NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TFPFUNHIS_pkey" PRIMARY KEY ("CODFUNHIS")
);

-- CreateTable
CREATE TABLE "TFPDEP" (
    "CODDEP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODFUN" BIGINT NOT NULL,
    "NOMEDEP" TEXT NOT NULL,
    "TIPODEP" TEXT NOT NULL,
    "DTNASC" DATE,
    "CGC" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TFPDEP_pkey" PRIMARY KEY ("CODDEP")
);

-- CreateTable
CREATE TABLE "TSIUSU" (
    "CODUSU" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMEUSU" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "CODFUN" BIGINT,
    "SITUACAO" TEXT NOT NULL DEFAULT 'ATIVO',
    "DHULTACESSO" TIMESTAMP(3),
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSIUSU_pkey" PRIMARY KEY ("CODUSU")
);

-- CreateTable
CREATE TABLE "TSXPAP" (
    "CODPAP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMEPAP" TEXT NOT NULL,
    "DESCRPAP" TEXT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,
    "CODUSUALT" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSXPAP_pkey" PRIMARY KEY ("CODPAP")
);

-- CreateTable
CREATE TABLE "TSXPERM" (
    "CODPERM" BIGSERIAL NOT NULL,
    "CHAVEPERM" TEXT NOT NULL,
    "DESCRPERM" TEXT NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TSXPERM_pkey" PRIMARY KEY ("CODPERM")
);

-- CreateTable
CREATE TABLE "TSXPAPPERM" (
    "CODPAPPERM" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODPAP" BIGINT NOT NULL,
    "CODPERM" BIGINT NOT NULL,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,

    CONSTRAINT "TSXPAPPERM_pkey" PRIMARY KEY ("CODPAPPERM")
);

-- CreateTable
CREATE TABLE "TSXUSUPAP" (
    "CODUSUPAP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODUSU" BIGINT NOT NULL,
    "CODPAP" BIGINT NOT NULL,
    "CODEMP" BIGINT,
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',

    CONSTRAINT "TSXUSUPAP_pkey" PRIMARY KEY ("CODUSUPAP")
);

-- CreateTable
CREATE TABLE "TAULOG" (
    "CODAUD" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "NOMETAB" TEXT NOT NULL,
    "CODREG" BIGINT NOT NULL,
    "OPERACAO" TEXT NOT NULL,
    "DADOSANT" JSONB,
    "DADOSNOVOS" JSONB,
    "MOTIVO" TEXT,
    "ORIGEM" TEXT NOT NULL,
    "DHALT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUALT" BIGINT,

    CONSTRAINT "TAULOG_pkey" PRIMARY KEY ("CODAUD")
);

-- CreateIndex
CREATE INDEX "TSIEMP_CODTEN_idx" ON "TSIEMP"("CODTEN");

-- CreateIndex
CREATE INDEX "TSIEMP_CODEMPMATRIZ_idx" ON "TSIEMP"("CODEMPMATRIZ");

-- CreateIndex
CREATE UNIQUE INDEX "TFPCAR_CODTEN_NOMECAR_key" ON "TFPCAR"("CODTEN", "NOMECAR");

-- CreateIndex
CREATE INDEX "TSICUS_CODTEN_idx" ON "TSICUS"("CODTEN");

-- CreateIndex
CREATE INDEX "TFPFUN_CODTEN_idx" ON "TFPFUN"("CODTEN");

-- CreateIndex
CREATE INDEX "TFPFUN_CODEMP_idx" ON "TFPFUN"("CODEMP");

-- CreateIndex
CREATE UNIQUE INDEX "TFPFUN_CODTEN_CODEMP_NUMCAD_key" ON "TFPFUN"("CODTEN", "CODEMP", "NUMCAD");

-- CreateIndex
CREATE INDEX "TFPFUNHIS_CODTEN_CODFUN_idx" ON "TFPFUNHIS"("CODTEN", "CODFUN");

-- CreateIndex
CREATE INDEX "TFPDEP_CODTEN_CODFUN_idx" ON "TFPDEP"("CODTEN", "CODFUN");

-- CreateIndex
CREATE UNIQUE INDEX "TSIUSU_CODFUN_key" ON "TSIUSU"("CODFUN");

-- CreateIndex
CREATE UNIQUE INDEX "TSIUSU_CODTEN_EMAIL_key" ON "TSIUSU"("CODTEN", "EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "TSXPAP_CODTEN_NOMEPAP_key" ON "TSXPAP"("CODTEN", "NOMEPAP");

-- CreateIndex
CREATE UNIQUE INDEX "TSXPERM_CHAVEPERM_key" ON "TSXPERM"("CHAVEPERM");

-- CreateIndex
CREATE INDEX "TSXPAPPERM_CODTEN_idx" ON "TSXPAPPERM"("CODTEN");

-- CreateIndex
CREATE UNIQUE INDEX "TSXPAPPERM_CODPAP_CODPERM_key" ON "TSXPAPPERM"("CODPAP", "CODPERM");

-- CreateIndex
CREATE INDEX "TSXUSUPAP_CODTEN_CODUSU_idx" ON "TSXUSUPAP"("CODTEN", "CODUSU");

-- CreateIndex
CREATE INDEX "TAULOG_CODTEN_NOMETAB_CODREG_idx" ON "TAULOG"("CODTEN", "NOMETAB", "CODREG");

-- AddForeignKey
ALTER TABLE "TSIEMP" ADD CONSTRAINT "TSIEMP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSIEMP" ADD CONSTRAINT "TSIEMP_CODEMPMATRIZ_fkey" FOREIGN KEY ("CODEMPMATRIZ") REFERENCES "TSIEMP"("CODEMP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPCAR" ADD CONSTRAINT "TFPCAR_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSICUS" ADD CONSTRAINT "TSICUS_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSICUS" ADD CONSTRAINT "TSICUS_CODEMP_fkey" FOREIGN KEY ("CODEMP") REFERENCES "TSIEMP"("CODEMP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSICUS" ADD CONSTRAINT "TSICUS_CODCENCUSPAI_fkey" FOREIGN KEY ("CODCENCUSPAI") REFERENCES "TSICUS"("CODCENCUS") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPFUN" ADD CONSTRAINT "TFPFUN_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPFUN" ADD CONSTRAINT "TFPFUN_CODEMP_fkey" FOREIGN KEY ("CODEMP") REFERENCES "TSIEMP"("CODEMP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPFUN" ADD CONSTRAINT "TFPFUN_CODCAR_fkey" FOREIGN KEY ("CODCAR") REFERENCES "TFPCAR"("CODCAR") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPFUN" ADD CONSTRAINT "TFPFUN_CODCENCUS_fkey" FOREIGN KEY ("CODCENCUS") REFERENCES "TSICUS"("CODCENCUS") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPFUNHIS" ADD CONSTRAINT "TFPFUNHIS_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPFUNHIS" ADD CONSTRAINT "TFPFUNHIS_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPDEP" ADD CONSTRAINT "TFPDEP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPDEP" ADD CONSTRAINT "TFPDEP_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSIUSU" ADD CONSTRAINT "TSIUSU_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSIUSU" ADD CONSTRAINT "TSIUSU_CODFUN_fkey" FOREIGN KEY ("CODFUN") REFERENCES "TFPFUN"("CODFUN") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXPAP" ADD CONSTRAINT "TSXPAP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXPAPPERM" ADD CONSTRAINT "TSXPAPPERM_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXPAPPERM" ADD CONSTRAINT "TSXPAPPERM_CODPAP_fkey" FOREIGN KEY ("CODPAP") REFERENCES "TSXPAP"("CODPAP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXPAPPERM" ADD CONSTRAINT "TSXPAPPERM_CODPERM_fkey" FOREIGN KEY ("CODPERM") REFERENCES "TSXPERM"("CODPERM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXUSUPAP" ADD CONSTRAINT "TSXUSUPAP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXUSUPAP" ADD CONSTRAINT "TSXUSUPAP_CODUSU_fkey" FOREIGN KEY ("CODUSU") REFERENCES "TSIUSU"("CODUSU") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXUSUPAP" ADD CONSTRAINT "TSXUSUPAP_CODPAP_fkey" FOREIGN KEY ("CODPAP") REFERENCES "TSXPAP"("CODPAP") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TSXUSUPAP" ADD CONSTRAINT "TSXUSUPAP_CODEMP_fkey" FOREIGN KEY ("CODEMP") REFERENCES "TSIEMP"("CODEMP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TAULOG" ADD CONSTRAINT "TAULOG_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ============================================================
-- SelX: Row Level Security por tenant (ADR-0002) + papel de aplicação
-- Regra: toda tabela com CODTEN ganha política RLS NA MESMA migration.
-- ============================================================

-- Papel de aplicação (dev/CI; em produção a role é provisionada pela operação
-- com senha própria — nunca reutilizar esta).
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'selx_app') THEN
    CREATE ROLE selx_app LOGIN PASSWORD 'selx_app_dev';
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO selx_app;
-- Sem DELETE: exclusao fisica de dado de negocio e proibida (Convencao de Banco §9)
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO selx_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO selx_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO selx_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO selx_app;

-- RLS: politica unica por tenant, usando a variavel de transacao app.codten
-- (SET LOCAL app.codten = '<codigo>' — ver ADR-0002).
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'TSIEMP','TSIUSU','TFPFUN','TFPFUNHIS','TFPDEP','TFPCAR','TSICUS',
    'TSXPAP','TSXPAPPERM','TSXUSUPAP','TAULOG'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY politica_tenant ON %I ' ||
      'USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) ' ||
      'WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)',
      t
    );
  END LOOP;
END $$;

-- Tabelas globais (TSXTEN, TSXPERM): sem politica de tenant; escrita restrita
-- a operacoes de plataforma. selx_app le, mas nao altera tenants/permissoes.
REVOKE INSERT, UPDATE ON "TSXTEN" FROM selx_app;
REVOKE INSERT, UPDATE ON "TSXPERM" FROM selx_app;
