-- CreateTable
CREATE TABLE "TFPCARCOMP" (
    "CODCARCOMP" BIGSERIAL NOT NULL,
    "CODTEN" BIGINT NOT NULL,
    "CODCAR" BIGINT NOT NULL,
    "NOME" TEXT NOT NULL,
    "DESCRICAO" TEXT,
    "NIVELESPERADO" INTEGER NOT NULL,
    "CRITICIDADE" TEXT NOT NULL DEFAULT 'MEDIA',
    "JUSTIFICATIVA" TEXT,
    "ORDEM" INTEGER NOT NULL DEFAULT 0,
    "ATIVO" CHAR(1) NOT NULL DEFAULT 'S',
    "DHINC" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CODUSUINC" BIGINT,
    "DHALT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TFPCARCOMP_pkey" PRIMARY KEY ("CODCARCOMP")
);

-- CreateIndex
CREATE INDEX "TFPCARCOMP_CODTEN_CODCAR_idx" ON "TFPCARCOMP"("CODTEN", "CODCAR");

-- AddForeignKey
ALTER TABLE "TFPCARCOMP" ADD CONSTRAINT "TFPCARCOMP_CODTEN_fkey" FOREIGN KEY ("CODTEN") REFERENCES "TSXTEN"("CODTEN") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TFPCARCOMP" ADD CONSTRAINT "TFPCARCOMP_CODCAR_fkey" FOREIGN KEY ("CODCAR") REFERENCES "TFPCAR"("CODCAR") ON DELETE RESTRICT ON UPDATE CASCADE;



-- SelX: RLS (ADR-0002) — competências esperadas do cargo são dados do tenant.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['TFPCARCOMP'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY politica_tenant ON %I USING ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint) WITH CHECK ("CODTEN" = NULLIF(current_setting(''app.codten'', true), '''')::bigint)', t);
  END LOOP;
END $$;
